export const companies = [
	'84.51°',
	'A Place For Mom',
	'AOL',
	'ASCAP',
	'AWL',
	'AbbVie',
	'Abnormal Security',
	'Acast',
	'Accolade',
	'Ada',
	'Adobe',
	'AdvaMed',
	'Advia Credit Union',
	'Advocate Aurora Health',
	'Affectiva',
	'Airbnb',
	'Aircall',
	'Alation',
	'Alcon',
	'Allbirds',
	'Allovue',
	'Allstate',
	'Altais',
	'Amazon',
	'American Express',
	'American International Group',
	'Amperity',
	'Andie',
	'Ankr',
	'Appfire',
	'Apple',
	'ApplyBoard',
	'Aramark',
	'Arcadia',
	'Ardoq',
	'Asana',
	'Ascend',
	'Asensus Surgical',
	'AssessFirst',
	'Atlassian',
	'Atmosphere',
	'Atos',
	'Audible',
	'Austin Pets Alive!',
	'Autodesk',
	'Automattic',
	'Avanade',
	'Avis',
	'Axios',
	'BIC',
	'BMC Software',
	'BMW of North America, LLC',
	'BNY Mellon',
	'BRICK Education Network',
	'Babylist',
	'Baker Tilly',
	'Bamboo Health',
	'Banfield Pet Hospital',
	'Bank of America',
	'Bankjoy',
	'Banner Health',
	'BayFirst',
	'Beam Suntory',
	'Beautycounter',
	'Best Buy',
	'Better',
	'BetterUp',
	'Biogen',
	'Bird',
	'BitGo',
	'Bitso',
	'Bixal',
	'Black Girl Sunscreen',
	'Black Girl Ventures Foundation',
	'BlackLine',
	'BlackRock',
	'Bloomberg LP',
	'BlueTriton',
	'Bluebeam',
	'Bluecore',
	'Blueprint Medicines',
	'Bombas',
	'Bombora',
	'Bond',
	'Booster',
	'Boston Consulting Group',
	'Boundless Immigration',
	'Bounteous',
	'Bowery Farming',
	'Bozzuto',
	'BrainPOP',
	'Bright Cellars',
	'Brilliant Earth',
	'Bristol Myers Squibb',
	'Broadridge',
	'Bullhorn, Inc.',
	'Burton Snowboards',
	'C.H. Robinson',
	'CEEK VR INC',
	'CSC',
	'CURLS',
	'CVS Health',
	'CapTech',
	'Capital One',
	'CarGurus',
	'CarMax',
	'Carbon',
	'Carbyne',
	'Cardlytics',
	'Care/of',
	'Carewell',
	'Carta',
	'Cash App',
	'Cerner',
	'Charles Schwab',
	'Checkout.com',
	'Checkr',
	'Chevron',
	'Chewy',
	'Chick-fil-A',
	'Chobani',
	'Choco',
	'Cinemark',
	'Cisco Meraki',
	'City National Bank',
	'City of Philadelphia',
	'Clarity AI',
	'Clearlink',
	'Cleo',
	'Cleveland Research Company',
	'Clover',
	'Cobalt',
	'Coca-Cola',
	'Cofense',
	'Coinbase',
	'Coleman Research',
	'Collins Aerospace',
	'Colonial Electric Supply',
	'Color Of Change',
	'Column',
	'Comcast',
	'Coney Island Prep',
	'Copper',
	'Coty',
	'Creative Office Pavilion',
	'Crescent Bank',
	'Cresco Labs',
	'CrossBorder Solutions',
	'CrowdStrike',
	'Cruise',
	'Cummins',
	'Curaleaf',
	'Cureatr, Inc.',
	'CyberCoders',
	'DHI Group, Inc.',
	'DIG',
	'DTCC',
	'Dandelion Energy',
	'Dell Technologies',
	'Delta Air Lines',
	'Dematic',
	'Depop',
	'Deutsche Bank',
	'Devoted Health',
	'Dialpad',
	'Dime Community Bank',
	'Discord',
	'Discover',
	'Dolby',
	'Dooly',
	'DoorDash',
	'Dow Jones',
	'Dropbox',
	'Droplette',
	'Duo Security',
	'Duolingo',
	'EPAM Systems',
	'EarnUp Inc',
	'EarthOptics',
	'EcoVadis',
	'Edwards Lifesciences',
	'Elastic',
	'Electric',
	'Elysium Health',
	'Energy Transfer Partners',
	'Engine No. 1',
	'Enlitic',
	'Enova',
	'Enterprise Holdings',
	'Epic Games',
	'Epic Insurance Brokers and Consultants',
	'Epsilon',
	'Equinox',
	'Equity Lifestyle Properties',
	'Esri',
	'Esusu Financial, Inc.',
	'Everbridge',
	'Exact Sciences',
	'Exelon',
	'Expel',
	'Explore Schools',
	'ExxonMobil',
	'Eze Castle Integration',
	'FOSSA',
	'FRONTSTEPS',
	'Factual',
	'Famous Supply',
	'FanDuel',
	'Fannie Mae',
	'FedEx',
	'Federal Bureau of Investigation (FBI)',
	'Federal Reserve Bank of Cleveland',
	'Fetch Robotics',
	'FinancialForce',
	'Fini Brand',
	'FireEye',
	'First Citizens Bank',
	'First Look Media',
	'First Republic Bank',
	'Fisher Investments',
	'Five to Nine',
	'Flatiron Health',
	'Flex',
	'Floating Point Group',
	'Flutterwave',
	'Food Bank For New York City',
	'Food52',
	'Ford Motor Company',
	'Founder Shield',
	'Framestore',
	'Freire Schools',
	'Freshworks',
	'GE Power',
	'GEICO',
	'Galileo Health',
	'GameChanger',
	'Gap Inc.',
	'Gemini',
	'General Motors',
	'Gentle Dental',
	'GeoBlue',
	'Giant Eagle',
	'GitLab',
	'Gladly',
	'Glaukos Corporation',
	'Gloat',
	'Global Endowment Management',
	'Globalization Partners',
	'Goldman Sachs',
	'Goosehead Insurance',
	'GroundTruth',
	'Growing Up Green Charter Schools',
	'GrubStreet',
	'Grubb Properties',
	'Grubhub',
	'Guardhat, Inc.',
	'Guidepoint',
	'HCSC',
	'HP',
	'Hachette Book Group',
	'Headspace',
	'Headway',
	'Healthfirst',
	'Helium Health',
	'Hello Alice',
	'Here Technologies',
	'Hero',
	'Highnote',
	'Hinge Health',
	'Hint',
	'Hiya',
	'Honeycomb',
	'Hootsuite',
	'Hopin',
	'Hotel Engine',
	'Howard Hughes Medical Institute',
	'Hudson River Trading',
	'Hulu',
	'Humana',
	'Humu, Inc',
	'Hunt Club',
	'Hurdle',
	'HydraFacial',
	'IGS',
	'Ibotta',
	'Ideal Image',
	'Illumio',
	'Immersive Labs',
	'Inflection',
	'Infogrid',
	'Insight Global',
	'Instacart',
	'Intapp',
	'Integral Ad Science',
	'Intel',
	'Intelliware Development',
	'InterVenn Biosciences',
	'Intermex',
	'Intersection',
	'Intradiem',
	'Intuit',
	'Invoice Cloud, Inc.',
	'Ironwood Pharmaceuticals',
	'J. J. Keller & Associates, Inc.',
	'JW Player',
	'Johnson & Johnson',
	'Jumio',
	'Juniper Square',
	'JustFix.nyc',
	'Kafene',
	'Kairos Power',
	'Kaplow Communications',
	'KeepTruckin',
	'Kendra Scott',
	'Kimberly-Clark',
	'Kin Insurance',
	'Kinaxis',
	'Kindbody',
	'KinderCare Learning Companies',
	'Kinesso',
	'Kiva',
	'Klarna',
	'Klaviyo',
	'KnowBe4',
	"Kohl's",
	'Kraft Heinz',
	'Kroger',
	'Kustomer',
	'KyotoCooling',
	'LVMH',
	'Labatt Breweries of Canada',
	'Labcorp',
	'Laika',
	'LeafLink',
	'Lemonade',
	'Lev',
	'Lever',
	'Liberty Mutual Insurance',
	'LifeWeb 360',
	'Liftoff',
	'Lighthouse Academies',
	'Lime',
	'Lincoln Center for the Performing Arts',
	'Live Nation Entertainment',
	'LiveRamp',
	'LoanStreet',
	'Lockheed Martin',
	'LogRocket',
	'LogicGate',
	'Logz.io',
	'Lucid',
	'LuckyTruck',
	'M2 Technologies',
	'MBI',
	'MLB',
	'MSCI',
	'MUFG',
	'Macquarie Group',
	'Mad*Pow',
	'Madison Logic',
	'March of Dimes',
	'MarketAxess',
	'Mars Inc.',
	'Mattel',
	'Maven Recruiting Group',
	'McKesson',
	'McKinsey',
	'McMaster-Carr',
	'MediaCom',
	'MediaRadar',
	'Medidata',
	'Medium',
	'Meero',
	'Memorial Sloan Kettering Cancer Center',
	'Mented Cosmetics',
	'Mentor Collective',
	'Merck',
	'Meritage Homes',
	'MetLife',
	'Meta',
	'MicroStrategy',
	'Microdesk, Inc.',
	'MikeWorldWide',
	'Miro',
	'Model N',
	'ModernLoop',
	'N26',
	'NEXT Insurance',
	'NFL',
	'NIKE, Inc.',
	'NTT DATA Services',
	'NVIDIA',
	'Nanit',
	'Natera',
	'Nationwide Insurance',
	'Naturalicious',
	'Navex',
	'Nearpod',
	'NetApp',
	'Network for Good',
	'NeuroLeadership Institute',
	'New York Life',
	'Newchip',
	'NextCapital',
	'Niantic',
	'Nielsen',
	'Nitro, Inc.',
	'Noom',
	'Northrop Grumman',
	'Northwell Health',
	'Novartis',
	'Nubank',
	'Nuvera Life Science Consulting',
	'Nylas',
	'Office Practicum',
	'Omni Interactions',
	'Oncopeptides Inc.',
	'Open Society Foundations',
	'Open Systems Healthcare',
	'Opendoor',
	'Optima Tax Relief',
	'Oscar Health',
	'Outbrain',
	'PCORI',
	'POLITICO Europe',
	'PTFS',
	'PURE Insurance',
	'Pabst Brewing Company',
	'Palo Alto Networks',
	'Panorama Education',
	'Paper',
	'Patagonia',
	'Patientory, Inc.',
	'Patreon',
	'PayPal',
	'Paychex',
	'Paysafe',
	'PepsiCo',
	'Pernod Ricard USA',
	'Perpay',
	'Personal Capital',
	'PetMeds',
	'Pex',
	'Pfizer',
	'Philips',
	'Pie Insurance',
	'Pilotly',
	'Pineapple Payments',
	'Pinterest',
	'Place Exchange',
	"Players' Lounge",
	'Plenty',
	'Plug Power',
	'Podium',
	'Point',
	'Portland Public Schools',
	'Promenade Group',
	'Propel Schools',
	'Protective Life',
	'Publix',
	'Pulte Mortgage',
	'PulteGroup',
	'PwC',
	'Q-Centrix',
	'Qualcomm',
	'Quantcast',
	'Quanterix',
	'Quicken Loans',
	'Quizlet',
	'Rakuten Americas',
	'Rapid Micro Biosystems',
	'Rapid7',
	'RapidSOS',
	'Raytheon BBN Technologies',
	'ReachMobi Inc',
	'Relay',
	'Reliable Robotics',
	'Reonomy',
	'Reputation.com',
	'Restoration Management Company',
	'Ribbon',
	'Right At School',
	'Riskified',
	'Robinhood',
	'Rock Content',
	'SEO (SPONSORS FOR EDUCATIONAL OPPORTUNITY, INC)',
	'SIRUM',
	'SP Industries',
	'SUSE',
	'SXSW',
	'Sabra Dipping Company',
	'Salamander Hotels & Resorts',
	'Salesforce',
	'Samba TV',
	'Samsung Electronics America',
	'Sanofi U.S.',
	'Scholly',
	'Scotiabank',
	'Sealed, Inc',
	'Second Closet',
	'Sedera',
	'SelectQuote',
	'Selina',
	'ServiceNow',
	'Share Local Media',
	'Shippo',
	'Shopify',
	'Shutterstock',
	'Signavio',
	'Signify',
	'SimplePractice',
	'Sinclair Broadcast Group',
	"Sir Kensington's",
	'Skillz',
	'Skyepoint Decisions',
	'Small Girls PR',
	'Smart City Apartment Locating',
	'SmartNews',
	'Snap',
	'Socure',
	'Sonatype Inc',
	'Spartan',
	'Spectrum',
	'Speedway',
	'Spire Collective',
	'Splunk',
	'SpotX',
	'Spryker',
	'Square',
	'Squarespace',
	'Stack Overflow',
	'Stantec',
	'State Farm',
	'State Street',
	'Stimulus, Inc.',
	'Storable',
	'Stord',
	'Strava',
	'Stryker',
	'Success Academy Charter Schools',
	'Summit Public Schools',
	'Sumo Logic',
	'Susco',
	'Sutherland',
	'Swiftly',
	'Sysco',
	'TE Connectivity',
	'TELUS International AI Inc.',
	'TIAA',
	'TMA - The Marketing Arm',
	'TS Imagine',
	'TYRA Beauty',
	'Taboola',
	'Taco Bell',
	'Take-Two Interactive Software',
	'Talend',
	'Tandem',
	'Tandym Group',
	'Target',
	'Taulia',
	'Teaching Strategies',
	'Tenaska',
	'Tend',
	'Terrapin Beer',
	'The Auto Club Group',
	'The Boeing Company',
	'The Home Depot',
	'The Knot Worldwide',
	'The Los Angeles Times',
	'The Muse',
	'The Wall Street Journal',
	'The Wally Shop',
	'The Washington Post',
	'Thomson Reuters',
	'Thought Machine',
	'TikTok',
	'Tile, Inc.',
	'Tipico - North America',
	'Tory Burch',
	'Tradeweb',
	'TransUnion',
	'Transportation Security Administration',
	'TriNetX',
	'TrialSpark',
	'Tribune Publishing',
	'Trimble',
	'TripActions',
	'Trustwave',
	'Tuft & Needle',
	'Twitch',
	'Twitter',
	'Tyson Foods',
	'U.S. Department of State',
	'USA TODAY NETWORK',
	'USAA',
	'Uber',
	'Udemy',
	'UnitedHealth Group',
	'UnitedMasters',
	'Upside',
	'Upswing',
	'Urban Bush Women',
	'VIZIO',
	'VMware Carbon Black',
	'Valence',
	'Vanguard',
	'Verizon Communications',
	'ViacomCBS Streaming',
	'Vimeo',
	'Visa',
	'Vivacity Tech PBC',
	'Viventium',
	'WW (WeightWatchers)',
	'Waldo',
	'Walmart',
	'Warby Parker',
	'Warner Bros. Discovery',
	'Warner Bros. Discovery Ottawa',
	'Wave',
	'Wealthfront',
	'Weber Metals',
	'WellPower (formerly MHCD)',
	'Wells Fargo',
	'William Grant & Sons',
	'Wilton Brands',
	'Wind River',
	'Windsor Communities',
	'Wiser',
	'Wistia',
	'World 50',
	'World Fuel',
	'Wounded Warrior Project',
	'Wunderkind',
	'Xometry',
	'Yandex',
	'Year Up',
	'Yext',
	'YipitData',
	'Yubico',
	'Zoox',
	'Zwift',
	'b atomic',
	'dysrupt',
	'eBay',
	'iPipeline',
	'iQmetrix',
	'iRhythm Technologies',
	'monday.com',
	'quip',
	'souk + SEPIA'
];
